spring:
  application:
    name: spring-boot-rocketmq5-demo-consumer
  rocketmq:
    endpoints: 192.168.10.67:8181
    push-consumer:
      topics:
        default-topic: tmkit-normal-topic2
      consumer-group:
        order: CID-DEV-SPRING_BOOT_ROCKETMQ_5_DEMO_CONSUMER-ORDER_GROUP
        common: CID-DEV-SPRING_BOOT_ROCKETMQ_5_DEMO_CONSUMER-COMMON_GROUP

