spring:
  application:
    name: rocketmq-spring-boot-example
  rocketmq:
    endpoints: 192.168.10.67:8181
    producer:
      default-normal-topic: tmkit-normal-topic2
      default-delay-topic: tmkit-delay-topic

